language: go

go:
  - 1.7
  - tip

os:
  - linux
  # - osx

install:
  - go get -d -v -t ./...
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - bash scripts/install-vim.sh
  - export PATH=$HOME/vim/bin:$PATH

before_script:
  - uname -a
  - which -a vim
  - vim --cmd version --cmd quit
  - go env

script:
  - go test -v -race ./...
  - goveralls -service=travis-ci
  - make lint
